# Generated by Django 5.0 on 2023-12-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acftdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='An24rv_F15_Atm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_alt', models.IntegerField()),
                ('t0', models.IntegerField()),
                ('t5', models.IntegerField()),
                ('t10', models.IntegerField()),
                ('t15', models.IntegerField()),
                ('t20', models.IntegerField()),
                ('t25', models.IntegerField()),
                ('t30', models.IntegerField()),
                ('t35', models.IntegerField()),
                ('t40', models.IntegerField()),
                ('t45', models.IntegerField()),
            ],
            options={
                'verbose_name': 'AN24RV F15 ATM',
                'verbose_name_plural': 'AN24RV F15 ATM',
            },
        ),
        migrations.AlterModelOptions(
            name='acfts',
            options={'verbose_name': 'Aircraft', 'verbose_name_plural': 'Aircraft'},
        ),
        migrations.AddField(
            model_name='acfts',
            name='mtow_gvpp',
            field=models.IntegerField(default=21000, verbose_name='MTOW ГВПП'),
        ),
        migrations.AddField(
            model_name='acfts',
            name='mtow_ivpp',
            field=models.IntegerField(default=21000, verbose_name='MTOW ИВПП'),
        ),
        migrations.AlterField(
            model_name='acfts',
            name='acft_id',
            field=models.CharField(max_length=10, verbose_name='Бортовой номер'),
        ),
        migrations.AlterField(
            model_name='acfts',
            name='emty_cg',
            field=models.FloatField(verbose_name='Центровка пустого ВС'),
        ),
        migrations.AlterField(
            model_name='acfts',
            name='emty_w',
            field=models.FloatField(verbose_name='Масса пустого ВС'),
        ),
        migrations.AlterField(
            model_name='acfts',
            name='type_acft',
            field=models.CharField(max_length=10, verbose_name='Тип ВС'),
        ),
    ]
