# Generated by Django 5.0 on 2023-12-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acftdata', '0002_an24rv_f15_atm_alter_acfts_options_acfts_mtow_gvpp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='an24rv_f15_atm',
            options={'verbose_name': 'AN24RV F15 ATM', 'verbose_name_plural': 'AN24RV F15 ATMs'},
        ),
    ]
