# Generated by Django 5.0 on 2023-12-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acftdata', '0003_alter_an24rv_f15_atm_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='an24rv_f15_atm',
            options={'verbose_name': 'AN24RV F15 ATM', 'verbose_name_plural': 'AN24RV F15 ATM'},
        ),
    ]
