# Generated by Django 5.0 on 2023-12-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acftdata', '0004_alter_an24rv_f15_atm_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='an24rv_f15_atm',
            old_name='t0',
            new_name='t00',
        ),
        migrations.RenameField(
            model_name='an24rv_f15_atm',
            old_name='t5',
            new_name='t05',
        ),
    ]
