# Generated by Django 5.0 on 2023-12-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acftdata', '0005_rename_t0_an24rv_f15_atm_t00_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acfts',
            name='mtow_gvpp',
            field=models.IntegerField(verbose_name='MTOW ГВПП'),
        ),
        migrations.AlterField(
            model_name='acfts',
            name='mtow_ivpp',
            field=models.IntegerField(verbose_name='MTOW ИВПП'),
        ),
    ]
