# Generated by Django 5.0 on 2023-12-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acftdata', '0006_alter_acfts_mtow_gvpp_alter_acfts_mtow_ivpp'),
    ]

    operations = [
        migrations.CreateModel(
            name='An24rv_F05_Atm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_alt', models.IntegerField()),
                ('t00', models.IntegerField()),
                ('t05', models.IntegerField()),
                ('t10', models.IntegerField()),
                ('t15', models.IntegerField()),
                ('t20', models.IntegerField()),
                ('t25', models.IntegerField()),
                ('t30', models.IntegerField()),
                ('t35', models.IntegerField()),
                ('t40', models.IntegerField()),
                ('t45', models.IntegerField()),
            ],
            options={
                'verbose_name': 'AN24RV F05 ATM',
                'verbose_name_plural': 'AN24RV F05 ATM',
            },
        ),
    ]
