# Generated by Django 5.0 on 2024-01-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acftdata', '0007_an24rv_f05_atm'),
    ]

    operations = [
        migrations.CreateModel(
            name='An24rv_F15_asda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asda', models.IntegerField()),
                ('slope_m2', models.IntegerField()),
                ('slope_0', models.IntegerField()),
                ('slope_2', models.IntegerField()),
                ('wind_h20', models.IntegerField()),
                ('wind_h15', models.IntegerField()),
                ('wind_h10', models.IntegerField()),
                ('wind_h05', models.IntegerField()),
                ('Wind_00', models.IntegerField()),
                ('wind_t05', models.IntegerField()),
                ('wind_t10', models.IntegerField()),
            ],
            options={
                'verbose_name': 'AN24RV F15 ASDA',
                'verbose_name_plural': 'AN24RV F15 ASDA',
            },
        ),
    ]
