# Generated by Django 5.0 on 2024-01-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acftdata', '0008_an24rv_f15_asda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='an24rv_f15_asda',
            old_name='Wind_00',
            new_name='wind_00',
        ),
    ]
