# Generated by Django 5.0 on 2024-01-07 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acftdata', '0010_an24rv_f15_tora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='an24rv_f15_tora',
            old_name='slope_1',
            new_name='slope_p1',
        ),
        migrations.RenameField(
            model_name='an24rv_f15_tora',
            old_name='slope_2',
            new_name='slope_p2',
        ),
    ]
