# Generated by Django 5.0 on 2023-12-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aiirport_id', models.CharField(max_length=10, verbose_name='aiirport_id')),
                ('faa_id', models.CharField(max_length=10, verbose_name='faa_id')),
                ('ICAO', models.CharField(blank=True, default='', max_length=4, verbose_name='ICAO')),
                ('IATA', models.CharField(blank=True, default='', max_length=3, verbose_name='IATA')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('city', models.CharField(max_length=10, verbose_name='city')),
                ('country', models.CharField(max_length=4, verbose_name='country')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('alevation', models.IntegerField(verbose_name='alevation')),
                ('timezone_index', models.IntegerField(verbose_name='timezone_index')),
                ('type_index', models.IntegerField(verbose_name='type_index')),
                ('is_towered', models.IntegerField(verbose_name='is_towered')),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
            },
        ),
    ]
